### ISSUE TITLE
Add hook in system separate to where scene is loaded

### ISSUE THREAD

**Issue by tqwewe** [nicopap/bevy-scene-hook#2]
I'd like to add a hook in a system to run whenever any scene is loaded. But it seems like I cannot do this since the component needs the `SceneInstance` component, which I don't have in my system.

For example:
```rust
pub(super) fn spawn_teleporters_from_scene(mut cmds: Commands) {
    cmds.spawn().insert(SceneHook::new(|entity, world, cmds| {
        println!("New scene loaded!");
    }));
}
```

**Comment by nicopap** [comment]
Specifically, `SceneHook` is a component that must be added to the same `Entity` that the `Handle<Scene>` in `SceneBundle`. This crate provides only the `SceneHook` component. Indeed, if I were to remove all documentation, the whole crate would be around 20 lines of code.

Adding a hook independent from specific scene entities is **out of scope for bevy-scene-hook**. However, you can get quite close using `SceneHook` with the following trick:

```rust
fn default_hook(&EntityRef, &mut EntityCommands) {
    // Define a default hook
}

#[derive(Bundle)]
struct MySceneBundle {
    pub hook: SceneHook,
    pub scene: Handle<Scene>,
    pub transform: Transform,
    pub global_transform: GlobalTransform,
    pub visibility: Visibility,
    pub computed_visibility: ComputedVisibility,
}
impl MySceneBundle {
    fn new(scene: Handle<Scene>) -> Self {
        // Empty function: this only adds the default hook.
        Self::new_with_hook(|_, _| {})
    }

    fn new_with_hook<F>(scene: Handle<Scene>, special_hook: F) -> Self 
    where
        F: Fn(&EntityRef, &mut EntityCommands) + Send + Sync + 'static
    {
        MySceneBundle {
            hook: SceneHook::new(|entity, commands| {
                default_hook(entity, commands);
                special_hook(entity, commands);
            }),
            scene,
            transform: default(),
            global_transform: default(),
            visibility: default(),
            computed_visibility: default(),
        }
    }
}
```

Now, replace all usages of `SceneBundle` with `MySceneBundle`.

If this is not sufficient (for example, you are using a 3rd party crate that spawns itself the scenes, and therefore cannot change the code where the scene is loaded) I'd suggest you clone the repo, delete/hide the documentation and look at the code yourself. You'll probably be able to come up with a satisfactory design. You probably want to take inspiration from [the run_hooks system](https://github.com/nicopap/bevy-scene-hook/blob/30c742634894c39a0628b2189cd1d317f3df7402/src/hook.rs#L102-L119)

**Comment by nicopap** [comment]
From re-reading the issue. I think there is a misconception about what this crate is supposed to do.

It is meant to be used in combination with the bevy native [`SceneBundle`](https://docs.rs/bevy/latest/bevy/prelude/struct.SceneBundle.html). Bevy helpfully adds the `SceneInstance` component to entities with the `Handle<Scene>` component whenever the scene is loaded into the world.

We use this component because that's the purpose of this library: changing entities in a scene after they are loaded.

From the code you shared here. It's unclear what you are trying to accomplish. Do you later add a `Handle<Scene>` to the entity you just spawned? If so, the hook will run when the scene loads.

If not, what do you expect `SceneHook` to do? Why not simply print the message in the system that spawns your teleporter?
